export const userRegisterLocator = {
    signuplink: 'a[href="/login"]',
    pageInfo: 'div.signup-form',
    nameInput: 'input[name="name"]',
    emailInput: 'input[data-qa="signup-email"]',
    signupBtn: 'button[data-qa="signup-button"]',
    errorMsg: 'p[style="color: red;"]',
    successMsg: 'p[style="color: green;"]',
    accountInformationHeading: 'h2:has-text("Enter Account Information")',
    genderMr: '#uniform-id_gender1',
    genderMrs: '#uniform-id_gender2',
    passwordInput: 'input[name="password"]',
    dayField: 'select[data-qa="days"]',
    monthField: 'select[data-qa="months"]',
    yearField: 'select[data-qa="years"]',
    newsletterCheckbox: '#newsletter',
    receiveOffersCheckbox: '#optin',
    firstNameInput: 'input[data-qa="first_name"]',
    lastNameInput: 'input[data-qa="last_name"]',
    companyInput: 'input[data-qa="company"]',
    address1Input: 'input[data-qa="address"]',
    address2Input: 'input[data-qa="address2"]',
    countryField: 'select[data-qa="country"]',
    stateInput: 'input[data-qa="state"]',
    cityInput: 'input[data-qa="city"]',
    zipcodeInput: 'input[data-qa="zipcode"]',
    mobileNumberInput: 'input[data-qa="mobile_number"]',
    createAccountBtn: 'button[data-qa="create-account"]'
};